/**
 * This file was generated by the Jeddict
 */
package type;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;

/**
 * @author owner
 */
@Entity
@NamedQuery(name = "TDepartment.findByDepartmentCode", query = "Select t from TDepartment t where t.departmentCode=:departmentCode")
public class TDepartment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long departmentId;

    @Column(unique = true)
    @Basic
    private String departmentCode;

    @Basic
    private String departmentName;

    public Long getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    public String getDepartmentCode() {
        return this.departmentCode;
    }

    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final TDepartment other = (TDepartment) obj;
        if (!java.util.Objects.equals(this.getDepartmentCode(), other.getDepartmentCode())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + (this.getDepartmentCode() != null ? this.getDepartmentCode().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "TDepartment{" + " departmentId=" + departmentId + ", departmentCode=" + departmentCode + ", departmentName=" + departmentName + '}';
    }

}