/**
 * This file was generated by the Jeddict
 */
package type;

import util.csv.annotation.CsvColumn;
import util.csv.annotation.CsvColumnFormula;
import util.csv.annotation.CsvConverter;
import util.csv.converter.builtin.CsvColumnDateConverter;
import util.converter.GenderConverter;
import type.Gender;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * @author owner
 */
@Entity(name = "TEmployee")
@Table(uniqueConstraints=@UniqueConstraint(name = "t_employee_unique_employee_code", columnNames="employeeCode"))
public class TEmployee implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer employee_id;
    
    @Basic
    @CsvColumn(field="社員コード")
    private String employeeCode;
    
    @Transient
    private String departmentCode;
    
    @Basic
    //--CSV パーサ
    @CsvColumn(field="氏名")
    private String name;

    @Basic
//    @Enumerated(EnumType.STRING)
    @Convert(converter = GenderConverter.class)
    //--CSV パーサ
    @CsvColumn(field="性別")
    @CsvConverter(converter = GenderConverter.class)
    private Gender gender;
    
    @Temporal(TemporalType.DATE)
    //--CSV パーサ
    @CsvColumn(field="生年月日")
    @CsvConverter(converter = CsvColumnDateConverter.class)
    private Date birthday;

    @Basic
    //--CSV パーサ
    @CsvColumn(field="電話番号")
    private String phone;

    @Basic
    //--CSV パーサ
    @CsvColumn(field="携帯電話")
    private String mobilePhone;

    @Basic
    //--CSV パーサ
    @CsvColumn(field="郵便番号")
    private String zipCode;

    @Basic
    //--CSV パーサ
    @CsvColumnFormula(formula="住所1 += 住所2 += 住所3 += 住所4 += 住所5")
    private String address;

    @Basic
    private String remarks;

    public Integer getEmployee_id() {
        return this.employee_id;
    }

    public void setEmployee_id(Integer employee_id) {
        this.employee_id = employee_id;
    }

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getDepartmentCode() {
        return departmentCode;
    }

    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Gender getGender() {
        return this.gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMobilePhone() {
        return this.mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    public String getZipCode() {
        return this.zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

}