//
// This file was generated by the Jeddict
//
package type;

import java.io.Serializable;
import javax.persistence.Embeddable;

@Embeddable
public class TGroupPK implements Serializable {

    private String userid;

    private String groupid;

    public TGroupPK() {
    }

    public TGroupPK(String userid, String groupid) {
        this.userid = userid;
        this.groupid = groupid;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getGroupid() {
        return this.groupid;
    }

    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final TGroupPK other = (TGroupPK) obj;
        if (!java.util.Objects.equals(this.getUserid(), other.getUserid())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getGroupid(), other.getGroupid())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + (this.getUserid() != null ? this.getUserid().hashCode() : 0);
        hash = 89 * hash + (this.getGroupid() != null ? this.getGroupid().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "TGroupPK{" + " userid=" + userid + ", groupid=" + groupid + '}';
    }

}