/**
 * This file was generated by the Jeddict
 */
package type;

import java.io.Serializable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

/**
 * @author Owner
 */
@Entity
@NamedQueries({
    @NamedQuery(name = "TGroup.findByUserid", query = "Select e from TGroup e WHERE e.tUser.userid = :userid")
    ,@NamedQuery(name = "TGroup.deleteByUserid", query = "Delete FROM TGroup e WHERE e.tUser.userid = :userid")
})
public class TGroup implements Serializable {

    @EmbeddedId
    private TGroupPK groupPK;

    @ManyToOne(optional = false, targetEntity = TUser.class)
    @JoinColumn(name = "USERID", referencedColumnName = "USERID", insertable = false, updatable = false)
    private TUser tUser;

    public TGroupPK getGroupPK() {
        return this.groupPK;
    }

    public void setGroupPK(TGroupPK groupPK) {
        this.groupPK = groupPK;
    }

    public TUser getTUser() {
        return this.tUser;
    }

    public void setTUser(TUser tUser) {
        this.tUser = tUser;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final TGroup other = (TGroup) obj;
        if (!java.util.Objects.equals(this.getGroupPK(), other.getGroupPK())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 47 * hash + (this.getGroupPK() != null ? this.getGroupPK().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "TGroup{" + " groupPK=" + groupPK + '}';
    }

}